// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// poi_cpp
Rcpp::NumericVector poi_cpp(const Rcpp::List poly_list, const double precision);
RcppExport SEXP _polylabelr_poi_cpp(SEXP poly_listSEXP, SEXP precisionSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::List >::type poly_list(poly_listSEXP);
    Rcpp::traits::input_parameter< const double >::type precision(precisionSEXP);
    rcpp_result_gen = Rcpp::wrap(poi_cpp(poly_list, precision));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_polylabelr_poi_cpp", (DL_FUNC) &_polylabelr_poi_cpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_polylabelr(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
