# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

poi_cpp <- function(poly_list, precision = 1.0) {
    .Call(`_polylabelr_poi_cpp`, poly_list, precision)
}

