# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

polyCentroid <- function(points, precision = 1.0) {
    .Call(`_polylabelr_polyCentroid`, points, precision)
}

